version: '3.6'

services:
  ffmpeg:
    # just here to download the ffmpeg image automatically
    image: jrottenberg/ffmpeg

  mediatimelinerenderer:
    build:
      context: ./docker/
      dockerfile: mediaTimelineRenderer.dockerfile
    environment:
      - PATH_HOST_MEDIA
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/mediaTimelineRenderer:ro
      - ${PATH_HOST_MEDIA}:${PATH_HOST_MEDIA}
    command: ${PATH_HOST_MEDIA} --postmortem True --log_level 10 --command_ffmpeg='docker run --rm -v {path_media}:{path_media}:ro jrottenberg/ffmpeg -loglevel quiet'

# docker-compose run --rm mediatimelinerenderer